using DynamicData;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Skyrim.Records.Tooling;
using Mutagen.Bethesda.Synthesis;
using Noggog;


namespace UnknownPotions
{
    public class Program
    {
        private static Lazy<Settings.Settings> _settings = null!;
        private static Lazy<UnknownPotions.Settings.ManualLists> _lists = null!;
        private const string UnkPotionPatchName = "UnknownPotionsPatch.esp";
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, UnkPotionPatchName)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetAutogeneratedSettings("Lists", "lists.json", out _lists)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.WriteLine("Running version: 0.2");
            List<ModKey> allmods = new();
            foreach (var mod in state.LoadOrder)
            {
                allmods.Add(mod.Key);
                Console.WriteLine(mod.Key);
            }

            //Swap to ResolveAllContexts instead of this garbage
            ILoadOrder<IModListing<ISkyrimModGetter>> startLoadOrder = state.LoadOrder;
            startLoadOrder.RemoveKey(state.PatchMod.ModKey);

            if (_settings.Value.CopyPotions)
            {
                CopyPotions(state);
            }

            if (_settings.Value.PatchLeveledLists)
            {
                CopyLeveledList(state, startLoadOrder);
            }
        }

        public static void CopyPotions(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {

            //Predefined Lists ("Test" needed for CACO - don't remove)
            List<string> potionTypeNames = new() { "Fortify", "Draught", "Resist", "Restore", "Invisibility", "Waterbreathing", "Damage", "Weakness", "Frenzy", "CurePoison", "CureDisease", "Potion", "Elixir", "Etherealize", "NightEye", "DetectLife" };
            List<string> poisonTypeNames = new() { "Poison", "Fear", "Paralyze", "Poison", "Drain", "Slow", "Venom" };
            List<string> bannedTypeNames = new() { "Food", "Blood", "SpellTome", "DummyPotion", "DefaultPotion", "Unk", "Test" };
            List<string> explicitTypeNames = new() { "BloodskalPotion" };

            //Add to Lists based on user input 
            if (!_lists.Value.PotionTypes.Contains("")) potionTypeNames.Add(_lists.Value.PotionTypes);
            if (!_lists.Value.PoisonTypes.Contains("")) poisonTypeNames.Add(_lists.Value.PoisonTypes);
            if (!_lists.Value.BannedTypes.Contains("")) bannedTypeNames.Add(_lists.Value.BannedTypes);
            if (!_lists.Value.ExplicitTypes.Contains("")) explicitTypeNames.Add(_lists.Value.ExplicitTypes);

            //Unknown Potion Effect
            if (!state.LinkCache.TryResolve<IMagicEffectGetter>("UNK_RandomEffectPot", out var unknownRandomEffect))
            {
                Console.WriteLine("***Can't Resolve UNK_RandomEffectPot Effect: " + unknownRandomEffect + " THIS IS NOT OKAY***");
                Thread.Sleep(3000);
            }
            
            //Unknown Potion Keyword
            if (!state.LinkCache.TryResolveIdentifier<IKeywordGetter>("UNK_UnknownPotion", out var unknownKeyword))
            {
                Console.WriteLine("***Can't Resolve UNK_UnknownPotion Keyword: " + unknownKeyword + " THIS IS NOT OKAY***");
                Thread.Sleep(3000);
            }

            //Lists
            List<FormKey> processedIngredients = new();
            List<FormKey> processedEffects = new();
            List<FormKey> processedPotions = new();
            int errorNumber = 0;

            //BEGIN POTION PATCHING
            Console.WriteLine(Environment.NewLine + "Patching Potions..." + Environment.NewLine);
            if (_settings.Value.ExtraLogging) Thread.Sleep(1000);

            foreach (IIngestibleGetter ingestible in state.LoadOrder.PriorityOrder.Ingestible().WinningOverrides().ToList())
            {
                //Check if previously run
                if (ingestible.EditorID is null) continue;
                if (processedIngredients.Contains(ingestible.FormKey))
                {
                    Console.WriteLine("Higher Priority found " + ingestible);
                    continue;
                }
                processedIngredients.Add(ingestible.FormKey);

                //Check if allowed to continue based on lists
                if (((potionTypeNames.Any(s => ingestible.EditorID.Contains(s)) || poisonTypeNames.Any(s => ingestible.EditorID.Contains(s))) && !bannedTypeNames.Any(s => ingestible.EditorID.Contains(s))) ||
                explicitTypeNames.Any(s => ingestible.EditorID.Contains(s))) goto FoundPotion;
                if (_settings.Value.ExtraLogging) Console.WriteLine("Found Non-Potion: " + ingestible);
                continue;

                //Begin Potion Modifying
            FoundPotion:
                processedPotions.Add(ingestible.FormKey);
                Console.WriteLine(" ");
                Console.WriteLine("Got Potion: " + ingestible);
                Ingestible newUnknownIngestible = state.PatchMod.Ingestibles.DuplicateInAsNewRecord(ingestible);

                Console.WriteLine("Effect(s) Found...");

                //Loop for each of the potion's effects
                foreach (var ingestibleEffect in newUnknownIngestible.Effects.ToList())
                {
                    if (!ingestibleEffect.BaseEffect.TryResolve(state.LinkCache, out var baseEffect))
                    {
                        Console.WriteLine("***Can't Resolve: " + baseEffect + " ***");
                        continue;
                    }

                    var EffectRecord = ingestibleEffect.BaseEffect.Resolve(state.LinkCache);
                    Console.WriteLine("Got Effect: " + EffectRecord);

                    //Check if previously run
                    if (processedEffects.Contains(EffectRecord.FormKey))
                    {
                        var processedUnkEffect = "Unk" + EffectRecord.EditorID;
                        //Error Checking
                        if (!state.LinkCache.TryResolveIdentifier<MagicEffect>(processedUnkEffect, out var EffectFormKey))
                        {
                            Console.WriteLine("Resolve Errored: " + processedUnkEffect);
                            errorNumber++;
                            continue;
                        }
                        Console.WriteLine($"Processed Record Added: {EffectFormKey}");
                        ingestibleEffect.BaseEffect.SetTo(EffectFormKey);
                        continue;
                    }

                    processedEffects.Add(EffectRecord.FormKey);

                    //Effect Modifying
                    var newEffect = state.PatchMod.MagicEffects.DuplicateInAsNewRecord(EffectRecord);
                    newEffect.EditorID = "Unk" + EffectRecord.EditorID;
                    Console.WriteLine("New Effect: " + newEffect);

                    newEffect.Name = "Unknown Effect";
                    newEffect.Description = "";

                    ingestibleEffect.BaseEffect.SetTo(newEffect);

                }

                //Potion Modifying
                newUnknownIngestible.Name = "Unknown Potion";
                newUnknownIngestible.Value = (newUnknownIngestible.Value / 75) + 20;
                newUnknownIngestible.EditorID = "Unk" + newUnknownIngestible.EditorID;

                newUnknownIngestible.Keywords ??= new ExtendedList<IFormLinkGetter<IKeywordGetter>>();
                newUnknownIngestible.Keywords.Add(unknownKeyword);

                //Adding randomizer effect to potion
                newUnknownIngestible.Effects.Add(new Effect()
                {
                    BaseEffect = unknownRandomEffect.FormKey.ToNullableLink<IMagicEffectGetter>(),
                    Data = new EffectData()
                    {
                        Magnitude = 0,
                        Duration = 0,
                        Area = 0
                    }
                });

            }
            Console.WriteLine("--------------------");
            Console.WriteLine($"Processed - {processedIngredients.Count} - Ingestibles");
            Console.WriteLine($"Found - {processedPotions.Count} - Potions");
            Console.WriteLine($"Potion Errors: {errorNumber}");
            Console.WriteLine("--------------------");

            if (_settings.Value.PatchPlacedObjects)
            {
                PotionObjectSwap(state, processedPotions);
            }
        }

        public static void CopyLeveledList(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, ILoadOrder<IModListing<ISkyrimModGetter>> startLoadOrder)
        {

            //Lists
            List<string> potionLists = new() { "Potion", "Poison" };
            List<string> bannedLists = new() { "Unk" };
            List<string> bannedTypeNames = new() { "Food", "Blood", "SpellTome", "DummyPotion", "DefaultPotion", "Recipe", "Unk", "AAA" };
            if (!_lists.Value.ListNames.Contains("")) potionLists.Add(_lists.Value.ListNames);
            if (!_lists.Value.BannedLists.Contains("")) bannedLists.Add(_lists.Value.BannedLists);
            if (!_lists.Value.BannedTypes.Contains("")) bannedTypeNames.Add(_lists.Value.BannedTypes);
            var processedLists = new HashSet<FormKey>();
            var processedPotionLists = new HashSet<FormKey>();
            var recurssivePotionLists = new HashSet<FormKey>();
            int errorNumber = 0;

            //BEGIN LEVELED LIST PATCHING
            Console.WriteLine(Environment.NewLine + "Patching Leveled Lists..." + Environment.NewLine);
            if (_settings.Value.ExtraLogging) Thread.Sleep(3500);


            foreach (ILeveledItemGetter leveledItemList in state.LoadOrder.PriorityOrder.LeveledItem().WinningOverrides())
            {
                int nullEntryCount = 0;

                //Check if previously run
                if (leveledItemList.EditorID is null) continue;
                if (processedLists.Contains(leveledItemList.FormKey))
                {
                    Console.WriteLine("Higher Priority found " + leveledItemList);
                    continue;
                }
                processedLists.Add(leveledItemList.FormKey);

                //Check if allowed to continue based on lists
                if (potionLists.Any(s => leveledItemList.EditorID.Contains(s)) && !bannedLists.Any(s => leveledItemList.EditorID.Contains(s))) goto FoundList;
                if (_settings.Value.ExtraLogging) Console.WriteLine("Found Non-Potion List " + leveledItemList);
                continue;

                //Begin List Modifying
            FoundList:
                Console.WriteLine("Got List " + leveledItemList);

                //Creates TEMP copy because mutable reasons
                var lvlCopy = leveledItemList.DeepCopy();
                if (_settings.Value.ExtraLogging && lvlCopy.Entries != null) Console.WriteLine($"Count: {lvlCopy.Entries.Count}");

                //Loop for each of the list's entries
                foreach (var itemEntry in lvlCopy.Entries.EmptyIfNull())
                {
                    if (itemEntry.Data is null) continue;
                    IItemGetter? resolvedEntry = itemEntry.Data.Reference.TryResolve(state.LinkCache);
                    if (_settings.Value.ExtraLogging) Console.WriteLine("Got Entry: " + resolvedEntry);
                    if (resolvedEntry is null) continue;

                    //Check entry for recursive type list
                    if (resolvedEntry.EditorID is null) continue;
                    if (resolvedEntry.EditorID.Contains("LItem"))
                    {
                        if (_settings.Value.ExtraLogging) Console.WriteLine("Recursive Potion List Found: " + resolvedEntry);
                        nullEntryCount++;
                        recurssivePotionLists.Add(lvlCopy.FormKey);
                        recurssivePotionLists.Add(resolvedEntry.FormKey);
                        continue;
                    }

                    //Check entry for banned potion type
                    if (bannedTypeNames.Any(s => resolvedEntry.EditorID.Contains(s)))
                    {
                        Console.WriteLine("Banned Potion Found: " + resolvedEntry);
                        nullEntryCount++;
                        continue;
                    }

                    //Check entry to ensure ingestible type
                    var entryType = resolvedEntry.DeepCopy();
                    if (entryType.GetType() != typeof(Ingestible))
                    {
                        Console.WriteLine("Entry Type: " + entryType.GetType());
                        nullEntryCount++;
                        continue;
                    }

                    var newleveledItemEntryID = "Unk" + resolvedEntry.EditorID;
                    Console.WriteLine("Entry Replaced: " + newleveledItemEntryID);

                    //Error Checking
                    if (!state.LinkCache.TryResolveIdentifier<Ingestible>(newleveledItemEntryID, out var associatedFormKey))
                    {

                        Console.WriteLine("Resolve Errored: " + newleveledItemEntryID);
                        errorNumber++;
                        continue;
                    }
                    itemEntry.Data.Reference.SetTo(associatedFormKey);
                    if (_settings.Value.ExtraLogging) Console.WriteLine("Set to: " + associatedFormKey);
                }

                //Check if list was modified at all and creates modified copy
                if (_settings.Value.ExtraLogging && nullEntryCount != 0) Console.WriteLine($"Entries Skipped: {nullEntryCount}");
                if (leveledItemList.Entries != null && nullEntryCount != leveledItemList.Entries.Count)
                {
                    Console.WriteLine($"Editing Leveled List... {lvlCopy}");
                    processedPotionLists.Add(lvlCopy.FormKey);
                    LeveledItem newUnknownList = state.PatchMod.LeveledItems.GetOrAddAsOverride(lvlCopy);
                }

                Console.WriteLine(" ");
            }

            //Status information
            Console.WriteLine("--------------------");
            Console.WriteLine($"Found - {processedLists.Count} - Lists");
            Console.WriteLine($"Modified - {processedPotionLists.Count} - Potion Lists");
            Console.WriteLine($"Leveled List Error Number: {errorNumber}");
            Console.WriteLine("--------------------");

            //Calls merchant patcher - requires the
            if (_settings.Value.PatchMerchantsFix) { MerchantPatcher.Run(state, startLoadOrder, _settings.Value.ExtraLogging); }

        }

        public static void PotionObjectSwap(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, List<FormKey> processedPotions)
        {

            var worldspaceCache = new WorldspaceCellLocationCache(state.LoadOrder.PriorityOrder.Cell().WinningContextOverrides(state.LinkCache));
            //Lists
            List<FormKey> processedPlaced = new();
            int processedIngestible = 0;
            int errorNumber = 0;
            List<string> merchantCellList = new() {"RiftenElgrimsElixirs", "SolitudeAngelinesAromatics", "WhiterunArcadiasCauldron", "MarkarthHagsCure", "DLC2TelMithrynApothecary",
                                                    "DawnstarMortarandPestle", "MorthalThaumaturgistsHut", "WindhelmWhitePhial", "FalkreathGraveConcoctions"};
            if (!_lists.Value.MerchantCells.Contains("")) merchantCellList.Add(_lists.Value.MerchantCells);

            //BEGIN PLACED OBJECT PATCHING
            Console.WriteLine(Environment.NewLine + "Patching Placed Potions..." + Environment.NewLine);
            if (_settings.Value.ExtraLogging) Thread.Sleep(3500);

            foreach (var placedPotion in state.LoadOrder.PriorityOrder.PlacedObject().WinningContextOverrides(state.LinkCache))
            {

                //TESTING ONLY DON'T FORGET TO DISABLE
                //Skip if unowned - to speed up for testing
                //if (!placedPotion.Record.Owner.TryResolve(state.LinkCache, out var owner)) continue;

                //Check if object is an ingestible
                if (!placedPotion.Record.Base.TryResolve<IIngestibleGetter>(state.LinkCache, out var placedObjectBase)) continue;
                if (_settings.Value.ExtraLogging) Console.WriteLine($"Found Ingestible: {placedObjectBase}");
                processedIngestible++;

                if (!processedPotions.Contains(placedPotion.Record.Base.FormKey))
                {
                    if (_settings.Value.ExtraLogging) Console.WriteLine($"Not a Potion {placedPotion.Record.Base.FormKey}");
                    continue;
                }

                //Check if object is in a shop cell
                if (placedPotion.TryGetContainingCell(worldspaceCache, out var cell))
                {
                    if (cell.Record.EditorID is null) continue;
                    if (merchantCellList.Any(s => cell.Record.EditorID.Contains(s)))
                    {
                        if (_settings.Value.ExtraLogging) Console.WriteLine($"Skipping Merchant Cell {cell.Record.FormKey}");
                        continue;
                    }
                }

                //Is a potion
                processedPlaced.Add(placedPotion.Record.Base.FormKey);

                //Modifying placed potion
                var placedPotionRecord = placedPotion.Record.Base.Resolve(state.LinkCache);
                var UnkPotionID = "Unk" + placedPotionRecord.EditorID;

                //Error checking
                if (!state.LinkCache.TryResolveIdentifier<Ingestible>(UnkPotionID, out var associatedFormKey))
                {
                    Console.WriteLine($"Resolve Errored: {UnkPotionID}");
                    errorNumber++;
                    continue;
                }

                //Create modified copy
                Console.WriteLine($"Replacing Potion - {placedPotion.Record.Base} - with - {UnkPotionID}");
                var overridePlaced = placedPotion.GetOrAddAsOverride(state.PatchMod);
                overridePlaced.Base.SetTo(associatedFormKey);
            }

            //Status information
            Console.WriteLine("--------------------");
            Console.WriteLine($"Processed - {processedIngestible} - Ingestibles");
            Console.WriteLine($"Replaced - {processedPlaced.Count} - Potions");
            Console.WriteLine($"Placing Errors: {errorNumber}");
            Console.WriteLine("--------------------");
        }

    }
}
